[package]
name = "image_processing"
version = "0.1.0"
edition = "2018"
authors = []

[dependencies]
image = { git = "https://github.com/image-rs/image" }
crossbeam = "0.7"
num_cpus = "1.0"
num-traits = "0.2"

[features]
display-window = ["sdl2"]

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["bundled"]
optional = true

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "histogram_specification"
harness = false 

# [[bench]]
# name = "histograms"
# harness = false

[profile.dev]
opt-level = 2 
debug = true
incremental = true
