[package]
name = "image_processing"
version = "0.1.0"
authors = []

[dependencies]
image = "0.20.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false 

[profile.dev]
opt-level = 3
debug = true
incremental = true
